language: node_js
node_js:
  - "7"
install:
  - npm install
  - npm run-script bower i -- --allow-root
script:
  - npm run-script pulp build
  - npm test
after_success:
  - >-
    test $TRAVIS_TAG &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
